### ISSUE TITLE
macOS 在git clone后出现错误

### ISSUE THREAD

**Issue by charlesbatel** [mownos/nvimisty#4]
![Uploading 331699004429_.pic.jpg…]()

**Comment by charlesbatel** [comment]
![WechatIMG77](https://github.com/mownos/nvimisty/assets/46130977/65dba217-b25b-42d6-9b48-55c43018409a)
macOS通过Homebrew安装后貌似只有0.9.4版本
所以需要手动安装0.10(next版本)

**Comment by mistricky** [comment]
You need v0.10.0 or higher version of Neovim to use the nvimisty, cause nvimisty is dependent on dropbar plugin that rely on v0.10.0 or higher version to reach out full experience of winbar.

**Comment by mistricky** [comment]
I missing nvim version requirements on README, I'll fix it later, thx for use nvimisty

**Comment by mistricky** [comment]
Fix on https://github.com/mownos/nvimisty/pull/5, if there are any problems I missed, please reopen this issue.
